Short: notify_fail() malfunctions in 3.2.6
From: Malcolm  Tester <MTester@cambric.com>
Date: Mon, 25 Oct 1999 11:04:32 -0600
Type: Bug
State: Done - irreproducible.

One other small problem I've noticed in 3.2.6, but doesn't seem to happen in
3.2.7.  You may be already aware of it.  the notify_fail() doesn't work
properly.  If I am carrying an object that defines a command "read", and the
room I am in defines a command "read", and the room's notify_fail says
something like "There is nothign here to read." and the object's
notify_fail() says "Read what?", and of course, if the argument doesn't
match, return 0; is done properly, you always get the object's "Read what?".
Let's say a proper argument for the room would be "read runes" and the
_only_ argument the object accepts is "read mail".  I can type "read runes"
or "read sdfhs" or anything besides "read mail", and I always get the
notify_fail() from the object I am carrying.  If I have more than one object
in my inventory that defines that command, only the first is checked.  I've
tested this a bit in 3.2.7, and the problem doesn't seem to exist there.

---------- Analysis ----------

I can't reproduce this problem, and I think that it was caused by
a badly programmed object. If there really were a problem with notify_fail(),
I'd have been swamped with similar bug reports.

